### ISSUE TITLE
Remove TensorFlow Addons (TFA) and utilize TF nightly to support python 3.9

### ISSUE THREAD

**Issue by lettergram** [capitalone/DataProfiler#111]
TensorFlow addons (TFA) are the primary reason the library cannot be upgraded. 

TFA is utilized in a single location in the code:

https://github.com/capitalone/DataProfiler/blob/f3cf74101d728422a316371d9bfcc7ef15ade506/dataprofiler/labelers/character_level_cnn_model.py#L274

It should be possible to create an F1 score metric function that doesn't require TFA:

https://stackoverflow.com/questions/64474463/custom-f1-score-metric-in-tensorflow

Once removed, tensorflow nightly would likely suffice and the library could then work on python 3.9.

Would we like to do this?

**Comment by AnhTruong** [comment]
fixed from https://github.com/capitalone/DataProfiler/pull/143
