### ISSUE TITLE
Add data.length

### ISSUE THREAD

**Issue by lettergram** [capitalone/DataProfiler#120]
**Is your feature request related to a problem? Please describe.**

I think the data class should have an easy-to-call property which gets the length of the given dataset, i.e. `data.length` instead of `len(data.data)`

**Comment by JGSweets** [comment]
or even `len(data)`

**Comment by JGSweets** [comment]
Maybe best to allow system to treat data as the dataset instead of having to `data.data`

**Comment by lettergram** [comment]
I think we can create:

* `data.length()`
* `data.cols()` or `data.keys()`

Could be relatively quick, but that'd help me

**Comment by JGSweets** [comment]
@lettergram sounds good, I'll work on `data.length` first then think about the others

**Comment by lettergram** [comment]
#125
