### ISSUE TITLE
Allow user to specify the default label for dp.train_structured_labeler

### ISSUE THREAD

**Issue by JGSweets** [capitalone/DataProfiler#140]
**Is your feature request related to a problem? Please describe.**
Currently, I have to change my dataset to train on it if a column doesn't contain the default label in its names

**Describe the outcome you'd like:**
The ability to specify my own default label when training on my data. 

**Additional context:**
potential function: `def dp.train_structured_labeler(data, default_label=None, save_dirpath=None, epochs=2)`
Also might suggest switching save path and epochs.

**Comment by AnhTruong** [comment]
fixed with https://github.com/capitalone/DataProfiler/pull/145
