### ISSUE TITLE
No error message when setting an option that doesnt exist

### ISSUE THREAD

**Issue by gme5078** [capitalone/DataProfiler#160]
**General Information:**
If you use the set function of profiler options, you will not get an error if you try to set something that doesn't exist. You should be getting an error or at least a warning.

**Comment by JGSweets** [comment]
Need to validate if this is still an issue with the changes to options recently.

**Comment by lettergram** [comment]
Appears to have been fixed

**Comment by JGSweets** [comment]
I still believe this can occur if someone were to choose a random text to start the option followed by any sub-level option pattern e.g.
```python
'fake.is_enabeled'
'fake.......text'
```
Not sure worth pursuing so not going to reopen it right now.
