### ISSUE TITLE
Inaccurate profile formats listed in README

### ISSUE THREAD

**Issue by scottiegarcia** [capitalone/DataProfiler#162]
**Please provide the issue you face regarding the documentation**
 
In [this section](https://github.com/capitalone/DataProfiler#what-is-a-data-profile) of the README, the types for `min` and `max` are float, but they are strings for datetime columns.

Additionally, I'm getting simply an int for `precision` instead of the dictionary defined in the readme.

**Comment by lettergram** [comment]
@scottiegarcia 

> Additionally, I'm getting simply an int for precision instead of the dictionary defined in the readme.

Release should be coming shortly, it's in the master - not in pypi

**Comment by scottiegarcia** [comment]
Also seeing `format` listed as a string but it is returned as a list of strings.

**Comment by lettergram** [comment]
#187 187
