### ISSUE TITLE
.zip version of DataProfiler 4.0.5 is empty

### ISSUE THREAD

**Issue by MohammedCoding** [capitalone/DataProfiler#214]
**General Information:**
 - OS: Chrome
 - Python version: 3.5.0
 - Library version: N/A

**Describe the bug:**
There are no files but Jupyter Notebooks in the .zip folder

**To Reproduce:**
Please make a new version with more visible .zip files

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Comment by MohammedCoding** [comment]
Expected Behavior: Good
Screenshots: N/A
Additional Context: I download the new version of DataProfiler (4.0.5) as a .zip file. After I checked the "important" files out: CODEOWNERS, README.TXT, etc. Then there were nothing but IPYNB files.

**Comment by JGSweets** [comment]
@MohammedCoding could you detail how you downloaded the zip file? I tried downloading the zip file directly from github and it contained all the necessary files on my end. 

Are you on windows? It shouldn't make a difference, but I am curious if that could cause any issue.

**Comment by MohammedCoding** [comment]
Sorry, It was a filter that made it show only IPYNB files.
