### ISSUE TITLE
Profile saving breaks when not using data labeler

### ISSUE THREAD

**Issue by scottiegarcia** [capitalone/DataProfiler#256]
**General Information:**
 - OS: Mac OS
 - Python version: 3.7
 - Library version: 0.5.0

**Describe the bug:**
The logic to handle removing data labeler info doesn't look before it leaps and tries to remove a key that doesn't exist.

**To Reproduce:**
```
import pandas as pd
import dataprofiler
from dataprofiler import Profiler, ProfilerOptions

df = pd.DataFrame([1,2,3], columns=["a"])

profile_options = ProfilerOptions()

profile_options.set({
    "data_labeler.is_enabled": False,
    "histogram_and_quantiles.is_enabled": False,
})

profile = Profiler(data=df, options=profile_options)

profile.save("test.json")  
```

**Expected behavior:**
Shouldn't hit code segment for removing data labeler info when it isn't used.

**Screenshots:**

**Additional context:**

**Comment by JGSweets** [comment]
Merged, will be avail in next release.
