### ISSUE TITLE
Sum not being returned in profiles by default

### ISSUE THREAD

**Issue by scottiegarcia** [capitalone/DataProfiler#262]
**General Information:**
 - OS:  MacOS Cataline 10.15.7
 - Python version: 3.7.10
 - Library version: 0.5.1

**Describe the bug:**
`sum` is not being returned by default for numerical columns. I'd understand if it were for performance reasons, but it appears that it is still being calculated since it has an entry in the `times` dictionary.

**To Reproduce:**
```
 import pandas as pd
import dataprofiler
from dataprofiler import Profiler, ProfilerOptions

df = pd.DataFrame([1,2,3], columns=["a"])

profile_options = ProfilerOptions()

profile_options.set({
    "data_labeler.is_enabled": False,
    "histogram_and_quantiles.is_enabled": False,
})

profile = Profiler(data=df, options=profile_options)

report = profile.report()

assert "sum" in report["data_stats"]["a"]["statistics"] 
```

**Expected behavior:**
Numeric columns should return `sum` by default in reports.

**Comment by JGSweets** [comment]
PR merged.
