### ISSUE TITLE
Disable output / silent option?

### ISSUE THREAD

**Issue by makkus** [capitalone/DataProfiler#265]
Would it be possible to have an option to disable any output / info messages when running the Profiler? I've had a look at the sources, and it seems simple `print`s are used, e.g. for:

```
Finding the Null values in the columns... (with 9 processes)
...
```
Maybe there could be a 'silent=True' option in the Profiler base class, or something similar? Having this output in the (standard) log(s) would still be useful, but as it is it gets in the way of my 'normal' command-line output, unless I apply some dodgy workarounds...

**Comment by JGSweets** [comment]
The readers currently use `logging`, possible we could update the rest of the library to do likewise.

**Comment by JGSweets** [comment]
@makkus did you have further thoughts on this, e.g. a mechanism to achieve.
like similar to TF?
`dp.get_logger().set_level('INFO')`

**Comment by makkus** [comment]
@JGSweets , sorry, what's TF? I don't really have a preference, and I guess it depends how you do it in the rest of the application. My personal use case would be to use DataProfiler as a library, so the main thing I'm concerned about is to not have any output to stdout/stderr. If I can can set the logging level and receive logging data for dataprofiler via the normal Python log mechanism, that'd be great, but it would be no dealbreaker for me to not have any logging output at all. This is just me though, not sure what your other users would like to see.

**Comment by JGSweets** [comment]
TF as in TensorFlow.

Logging would allow you to set the log level for output to console.

**Comment by makkus** [comment]
Right. I have never used TensorFlow, so can't comment there. But this sounds pretty much like the standard way to deal with logs in Python, right? Like letting me set something like:

```
import logging
logging.basicConfig(filename='example.log', encoding='utf-8', level=logging.DEBUG)
```
And then do logger-name-specific config if necessary (e.g. have different log levels for different libraries -- I personally seldomly need to do taht). If that's the case, in my opinion that would be the best option, yes.

**Comment by ChrisWallace2020** [comment]
@makkus the 2 PRs above (#357, #368) should resolve the issue. 

The `prints` were replaced with `logging.info` so that the effective level may be set high enough to filter them out if you choose to do so. This can be set either through `logging` like normal or you can use the function `set_verbosity` we've written in `dp_logging.py` that takes in the `logging` level (`logging.DEBUG`, `logging.INFO`, `logging.WARNING` etc). DataProfiler-specific logging will output to `stdout` (if left verbose). 

I hope this addresses your issue, let me know if there is any further feedback.

**Comment by makkus** [comment]
@ChrisWallace2020 thanks, much appreciated! I just tried out the latest version from git, and it works exactly as advertised for me, once I switchto logging.WARNING. 

Actually, there was one warning still intact:

```
/home/markus/projects/dharpa/.direnv/python-3.9.6/lib/python3.9/site-packages/dataprofiler/profilers/profile_builder.py:584: RuntimeWarning: 

!!! WARNING Partial Profiler Failure !!!

Profiling Type: data_labeler
Exception: ModuleNotFoundError
Message: No module named 'tensorflow'

For labeler errors, try installing the extra ml requirements via:

$ pip install dataprofiler[ml] --user


  utils.warn_on_profile('data_labeler', e)
```

But I can turn that off easily by disabling the data_labeler in the profile options. But it's probably a good idea to do that explicitly anyway -- even if though I deliberately did not install tensorflow on purpose, so I did not expect this to work. And since it's a different sort of warning it probably makes sense to leave that one in.

Thanks again!
