### ISSUE TITLE
https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/profilers/numerical_column_stats.py#L17

### ISSUE THREAD

**Issue by makkus** [capitalone/DataProfiler#289]
**General Information:**
 - OS: Ubuntu 20.10
 - Python version: 3.9
 - Library version: 0.5.2

**Describe the bug:**

The scipy dependency is not included in the default installation dependencies of DataProfiler, which means a simple ``import dataprofiler.profilers`` will error out when not using any of the extra package profiles when installing this package.

I believe this is the line responsible: https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/profilers/numerical_column_stats.py#L17

But there might be other places where scipy is imported, haven't checked.

**To Reproduce:**
```
pip install DataProfiler
# then, in repl:

➜ python
Python 3.9.2 (default, Jun 14 2021, 11:37:57) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dataprofiler.profilers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/markus/temp/venv/.venv/lib/python3.9/site-packages/dataprofiler/__init__.py", line 2, in <module>
    from .profilers.profile_builder import StructuredProfiler, \
  File "/home/markus/temp/venv/.venv/lib/python3.9/site-packages/dataprofiler/profilers/__init__.py", line 2, in <module>
    from .numerical_column_stats import NumericStatsMixin
  File "/home/markus/temp/venv/.venv/lib/python3.9/site-packages/dataprofiler/profilers/numerical_column_stats.py", line 17, in <module>
    import scipy.stats
ModuleNotFoundError: No module named 'scipy'
>>> 
```

**Expected behavior:**

Either scipy library is already installed (and included in default installation profile as dependency), or the module in question is not loaded. Or the metadata that is produced by the module in question is not extracted from the data.

**Comment by JGSweets** [comment]
Will release a fix for pypi as soon as it is merged. Thanks for identifying the bug.

**Comment by JGSweets** [comment]
@makkus The release has been made, should be about 2 min before 0.5.3 is available.

**Comment by makkus** [comment]
Cool, thanks! Can confirm that it works for me.
