### ISSUE TITLE
Training on new data 

### ISSUE THREAD

**Issue by kvrameshreddy** [capitalone/DataProfiler#35]
While training on new data in Colab the following data appears.

![default_label_error](https://user-images.githubusercontent.com/49742709/109650162-ddad0200-7b82-11eb-9f60-62526bd0859a.JPG)

When i change any one of the column name to "BACKGROUND" then the labeler gets trained and giving the following output.

![gives_error_but_model_saves](https://user-images.githubusercontent.com/49742709/109650301-08975600-7b83-11eb-8921-5fd3af3d5468.JPG)

To reproduce the errors Please use the following csv files
[datasets.zip](https://github.com/capitalone/DataProfiler/files/6068694/datasets.zip)

And while Predicting the Labeler gives prediction for each cell. How to Aggregate them to column level. Please help me in this
Thank you

**Comment by lettergram** [comment]
@kvrameshreddy appreciate you logging this, the correct function should be `save_to_disk`, as opposed to `save`.

Also, we will discuss adding a default_label option, at the moment `BACKGROUND` is required (as noted) for this function. 

Note, the given dataset you have has many columns with low integer values, I suspect the model will not perform well as all those numbers look effectively the same.
