### ISSUE TITLE
Column level Detection While using labeler

### ISSUE THREAD

**Issue by kvrameshreddy** [capitalone/DataProfiler#36]
**Is your feature request related to a problem? Please describe.**

When we predict using labeler.predict(data) we are getting cell level labels.

**Describe the outcome you'd like:**
How to get output as column level labels

**Additional context:**
And when we train new Labeler with custom data how to include the new labeler model into profiler while profiling the data to get Data_Label in the Json output.

Thankyou

**Comment by JGSweets** [comment]
@kvrameshreddy Thank you for the feature request. 
We currently utilize the profiler aspect of the library to provide column level labeling with respect to labeler cell level results.

It is not out of the question that a future model iteration could provide column level feedback.


For reference, if you would like to get column results right now using the profiler, you can use the profiler which will add additional statistics, or you could directly call the profiler for data labeling (this is fed column by column)
For using the profiler in general:
```python
import dataprofiler as dp

<import data>
.
.

profile = Profiler(data) # Calculate Statistics, Entity Recognition, etc
human_readable_report = profile.report(report_options={"output_format":"pretty"})

# data labels are assigned to each column in the `data_stats` key
human_readable_report['data_stats']["<COLUMN_NAME"]["data_label"]
```

Additionally, I should note you can turn off the other profiling features by setting the options such that only the data_labeler is utilized.

**Comment by JGSweets** [comment]
Closing this issue as there has not been activity for almost 1 year.
