### ISSUE TITLE
Add training and extended training with an example dataset

### ISSUE THREAD

**Issue by kvrameshreddy** [capitalone/DataProfiler#40]
**Please provide the issue you face regarding the documentation**
When using extended training,
when i pass custom label with custom data the following error appears
![error_while transfer_learning](https://user-images.githubusercontent.com/49742709/109766926-d6d2cd80-7c1c-11eb-8dc5-f038b4c8afa1.JPG)

When i add "BACKGROUND" In labels. Labler is getting trained. when i predict entities. the prediction is as follows
![err1](https://user-images.githubusercontent.com/49742709/109804305-1bc02980-7c48-11eb-9833-396db1bc8185.PNG)

to reproduce the error please use the following data
[new _data_label.zip](https://github.com/capitalone/DataProfiler/files/6074177/new._data_label.zip)

Please Update the Documentation with a example data, So that it will be helpful .

Thankyou

**Comment by lettergram** [comment]
Appreciate the additional feedback, the documentation was updated, see:

https://github.com/capitalone/DataProfiler#extending-a-data-labeler-with-transfer-learning

If you'd like to add new custom labels when transfer learning, you have to do the following:

```python
# NOTE: if you want to extend the data labels as oppose to replace with your own,
#       you will need to extend the labels list passed into the fit function:
#       e.g. labels = data_labeler.labels + ['new_label_1', 'new_label_2', ...]

# this will use transfer learning to retrain the data labeler on your new 
# dataset and labels.
# NOTE: data must be in an acceptable format for the preprocessor to interpret.
#       please refer to the preprocessor/model for the expected data format.
#       Currently, the DataLabeler cannot take in Tabular data, but requires 
#       data to be ingested with two columns [X, y] where X is the samples and 
#       y is the labels.
model_results = data_labeler.fit(x=data['samples'], y=data['labels'], 
    validation_split=0.2, epochs=2, labels=labels)
```

The current labels that exist are listed in the readme, if you'd simply like to extend them.

@JGSweets will be working on examples in the future, which would likely include some sample data.

**Comment by kvrameshreddy** [comment]
Hi @lettergram,

When we add custom labels to the existing labels, i am facing the following issue
![pad_error](https://user-images.githubusercontent.com/49742709/109938186-be82b180-7cf5-11eb-97b3-9fa2146894ee.JPG)

I think the problem is with label_mapping internally. 

Please take a look into this. Thankyou

**Comment by lettergram** [comment]
**This hasn't been added to pypi**, but the method to extend labels has been updated and the documentation is available in the README.  There should be a new release in the next day or so.

Here's the new documentation: https://github.com/capitalone/DataProfiler#extending-a-data-labeler-with-transfer-learning

You could install the library via building it on github or waiting for the next release (by Friday).
