### ISSUE TITLE
Numerical stats for string columns?

### ISSUE THREAD

**Issue by ian-contiamo** [capitalone/DataProfiler#409]
I do not understand why numerical statistics are returned for a string column. I feel like I'm missing something, but if this is a bug, I'll be happy to provide more details (I'm running the latest version, 0.7.1).

Here is a simplified version of the results for the text column:
```json
      "data_type": "string",
      "samples": ["Zachary Rojas", "Alexis Fox", "Alyssa Phillips"],
      "statistics": {
        "min": 7.0,
        "max": 26.0,
        "mode": [13.0],
        "sum": 66417.0,
        "mean": 13.2834,
        "variance": 5.50778599719944,
        "stddev": 2.3468672730257754,
        "data_label_representation": {
          "UNKNOWN": 0.733,
          "PERSON": 0.263,
          "US_STATE": 0.004,
          "INTEGER": 0.0,
          "FLOAT": 0.0,
          "QUANTITY": 0.0,
          "ORDINAL": 0.0
        }
      }
```
I include the data label representation, because it shows that the profiler does not find numerical values at all in this column. So what is the meaning of numerical stats for a pure text column?

PS. I could disable numerical statistics for text columns, but it's cumbersome (all statistics have to be enumerated: sum, variance, histograms...) and I would like to understand the default results of the profiler.

**Comment by JGSweets** [comment]
@ian-contiamo it is returning the statistics of the string length. While intended it is not necessarily clear.

However, you can disable numerical stats for strings with a single option via:
```
import dataprofiler as dp

options = dp.ProfilerOptions()
options.set({'text.is_numeric_stats_enabled': False})
```

**Comment by ian-contiamo** [comment]
Thanks, that makes a lot of sense!
