### ISSUE TITLE
Issue With DataLabeler

### ISSUE THREAD

**Issue by kvrameshreddy** [capitalone/DataProfiler#46]
When we load default data labeler and predict on a data set the output is as follows

![base_model](https://user-images.githubusercontent.com/49742709/110095164-9f058a80-7dc2-11eb-85d2-9d77b01e2979.PNG)
![base_model_prediction](https://user-images.githubusercontent.com/49742709/110095157-9d3bc700-7dc2-11eb-8acf-7c9185d2342f.PNG)

Here I want to make model learn on new label. So used transfer learning, The predictions after transfer learning are not good
![transfer_learning](https://user-images.githubusercontent.com/49742709/110095485-fe639a80-7dc2-11eb-994c-96c86e3a7d2e.PNG)
![new_model_predictions](https://user-images.githubusercontent.com/49742709/110095491-ff94c780-7dc2-11eb-92a9-72e5b8d48f90.PNG)

When compared to original predictions to this all the values disturbed. How to make model learn on new label without loosing original behavior. Please suggest me how to do it or  am i doing any thing wrong here.

To reproduce the results use this datasets
[data.zip](https://github.com/capitalone/DataProfiler/files/6089507/data.zip)

Thankyou.

**Comment by JGSweets** [comment]
Adding new labels is a delicate process currently. Depending on the model, sensitivity to training can alter the results of previous labeling. The current model uses a CNN, hence adding a label and only training on data with only the new label may shift the dataset. Additionally, the amount of training samples or epcohs used could navigate the model away from the original learned behavior.

I do want to note that we are adding a more streamlined mechanism for adding labels to the labeler which we will share as soon as we can. This hopefully will make the process easier/intuitive for adding new labels.

**Comment by kvrameshreddy** [comment]
Hi @JGSweets,

When can we expect latest release with updated transfer learning feature.

Thankyou.

**Comment by lettergram** [comment]
@kvrameshreddy Apologies, you should be able to pull the latest release from pypi now (as of last friday).

`pip install dataprofiler[ml] --upgrade`

Let us know if you have any other issues! As @JGSweets mentioned, adding new labels is a delicate process as you're actively training a model (via transfer learning). Without a substantial amount of data the model may not learn appropriately. IA model can easily be confused without a lot of clearly defined examples.
