### ISSUE TITLE
Detecting CSV integer header w/ description above it

### ISSUE THREAD

**Issue by JGSweets** [capitalone/DataProfiler#59]
**General Information:**
 - OS: Ubuntu 18.04
 - Python version: 3.8.7
 - Library version: 0.3.4

**Describe the bug:**
Currently, if there's a description above a header made of numbers, CSVData will not detect the integer header set.

**Expected behavior:**
Header should be detected at the proper line. despite a description being above it.

Reference to discussion: https://github.com/capitalone/DataProfiler/pull/56#discussion_r594448602

**Comment by lettergram** [comment]
This was fixed in PR #75, will add a test in next PR (validated locally)
