### ISSUE TITLE
Static Type Hinting: `dataprofiler/validators/base_validators.py`

### ISSUE THREAD

**Issue by taylorfturner** [capitalone/DataProfiler#605]
**Is your feature request related to a problem? Please describe.**
Improve the project in the area of 
- Make collaboration and code contribution easier
- Getting started with the code when a contributor is new to the code base

**Describe the outcome you'd like:**
Utilizing types from [mypy](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html) documentation for python3, implement type hinting in `dataprofiler/validators/base_validators.py`.

**Additional context:**
- [mypy](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html) documentation
- [Why use python types?](https://medium.com/vacatronics/why-you-should-consider-python-type-hints-770e5cb1570f)

**Comment by vindhyanairlj** [comment]
Working this

**Comment by taylorfturner** [comment]
Thanks, @vindhyanairlj! Appreciate the contribution! 🚀
