### ISSUE TITLE
Static Type Hinting: `dataprofiler/reports/utils.py`

### ISSUE THREAD

**Issue by taylorfturner** [capitalone/DataProfiler#606]
**Is your feature request related to a problem? Please describe.**
Improve the project in the area of 
- Make collaboration and code contribution easier
- Getting started with the code when a contributor is new to the code base

**Describe the outcome you'd like:**
Utilizing types from [mypy](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html) documentation for python3, implement type hinting in `dataprofiler/reports/utils.py`.

**Additional context:**
- [mypy](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html) documentation
- [Why use python types?](https://medium.com/vacatronics/why-you-should-consider-python-type-hints-770e5cb1570f)

**Comment by stefanycoimbra** [comment]
I'm working on this issue

**Comment by taylorfturner** [comment]
PR #640 resolved this issue. Thanks again, @stefanycoimbra!
