### ISSUE TITLE
Static Type Hinting: `dataprofiler/data_readers/`

### ISSUE THREAD

**Issue by taylorfturner** [capitalone/DataProfiler#610]
**Is your feature request related to a problem? Please describe.**
Improve the project in the area of 
- Make collaboration and code contribution easier
- Getting started with the code when a contributor is new to the code base

**Describe the outcome you'd like:**
Utilizing types from [mypy](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html) documentation for python3, implement type hinting in the `dataprofiler/data_readers/` folder. In this case, because there are multiple files in the folder, at the very minimum the changes should be partitioned out into multiple Pull Requests (PRs). Potentially this could go so far as 1 PR --> 1 file update with type hints.

**Additional context:**
- [mypy](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html) documentation
- [Why use python types?](https://medium.com/vacatronics/why-you-should-consider-python-type-hints-770e5cb1570f)

**Comment by taylorfturner** [comment]
Because this folder is so large, I recommend making more PRs that are smaller (3 - 4 files at a time / keep the net diff number lower when possible).

**Comment by taylorfturner** [comment]
@Sanketh7 just these last three PRs and this will be complete? Is that right?

**Comment by Sanketh7** [comment]
> @Sanketh7 just these last three PRs and this will be complete? Is that right?

There are 2 more files that need static typing but these are very short and I'll have a PR for them up soon.

**Comment by taylorfturner** [comment]
All merged. Closing. Thanks @Sanketh7
