### ISSUE TITLE
NoReturn on base_validator.py

### ISSUE THREAD

**Issue by taylorfturner** [capitalone/DataProfiler#639]
**General Information:**
add `NoReturn` on base_validator where there is no return value 

https://stackoverflow.com/questions/48038149/noreturn-vs-none-in-void-functions-type-annotations-in-python-3-6

**Comment by tonywu315** [comment]
The return type should be `None` because the function terminates and does not always throw an exception.

**Comment by taylorfturner** [comment]
PR merged! Thanks @tonywu315
