### ISSUE TITLE
Missing Diff section in unstructured profilers

### ISSUE THREAD

**Issue by JGSweets** [capitalone/DataProfiler#651]
**Please provide the issue you face regarding the documentation**
Need to mimic the diff section in structured_profilers: https://github.com/capitalone/DataProfiler/blob/main/examples/structured_profilers.ipynb

Add to unstructured_profilers example

**Comment by taylorfturner** [comment]
#877

**Comment by taylorfturner** [comment]
Closing due to fix in PR #877
