### ISSUE TITLE
Chardet d has trouble identifying some file encodings

### ISSUE THREAD

**Issue by JGSweets** [capitalone/DataProfiler#66]
**General Information:**
 - Python version: 3.8.7
 - Library version: 0.3.4

**Describe the bug:**
Currently the library uses chardet to determine file encodings, however it was relatively unmaintained until recently (Dec 2020) in addition to having trouble detecting some file encodings.

For example:
UTF-8 being detected as windows-1254: https://github.com/chardet/chardet/issues/148

**Additional context:**
Potential fixes include: 
https://hackernoon.com/how-i-used-python-to-solve-declareless-encoding-madness-hk1k42d3o

**Comment by sagars729** [comment]
Here is a PR: https://github.com/capitalone/DataProfiler/pull/112
charset_normalizer has a higher accuracy, but it is slower and requires a new requirement

**Comment by lettergram** [comment]
I think we need a test file to compare against @JGSweets if you have any, I think it'll be useful for an eval of approaches
