### ISSUE TITLE
Investigate use of cast() in data_readers

### ISSUE THREAD

**Issue by Sanketh7** [capitalone/DataProfiler#717]
Investigate whether these instances of `cast()` are needed. 
PRs should be small (at most a few files).

data_readers/csv_data.py
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/csv_data.py#L553
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/csv_data.py#L574
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/csv_data.py#L602
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/csv_data.py#L605

data_readers/data_utils.py
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/data_utils.py#L330
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/data_utils.py#L661

data_readers/data.py
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/data.py#L66

data_readers/filepath_or_buffer.py
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/filepath_or_buffer.py#L91
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/filepath_or_buffer.py#L101

data_readers/graph_data.py
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/graph_data.py#L255 
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/graph_data.py#L257

data_readers/structured_mixins.py
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/structured_mixins.py#L83

data_readers/text_data.py
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/text_data.py#L87 
- https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/text_data.py#L103

**Comment by junholee6a** [comment]
For most of these `cast`s, removing them causes an error when the file is type-checked with mypy. I think it is safe to assume that we don't have to investigate those further? Here are the ones that do _not_ cause mypy errors if you remove them (with updated line numbers):

data_readers/csv_data.py
* https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/csv_data.py#L572
* https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/csv_data.py#L603

data_readers/data.py
* https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/data.py#L65

data_readers/graph_data.py
* https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/graph_data.py#L255

data_readers/structured_mixins.py
* https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/structured_mixins.py#L83

I'm gonna go through these ones in a bit more detail.

**Comment by taylorfturner** [comment]
Thanks, @junholee6a -- great update on the line numbers too and appreciate you looking into these!

**Comment by junholee6a** [comment]
No problem @taylorfturner, thank you for the kind words! It seems like all but one of the five instances can be removed. The one that should probably not be removed is:
https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/data_readers/structured_mixins.py#L83

The reason removing this `cast()` doesn’t cause a mypy error is because `data` has type `Any`, while the function’s return type is `List[str]`. Since we’re certain that `data` will contain a list of strings, it is good practice to cast here so that the `Any` type doesn't propogate.

I'll make individual PRs for the rest since they all have different reasons

**Comment by taylorfturner** [comment]
Sounds great to break the PRs up in small chunks -- thx again, @junholee6a

**Comment by junholee6a** [comment]
I think this issue is resolved now

**Comment by taylorfturner** [comment]
Thanks again, @junholee6a! And yes, resolved. Will close with this comment. Thx!
