### ISSUE TITLE
profiler/utils.py contains GPL code

### ISSUE THREAD

**Issue by leos** [capitalone/DataProfiler#727]
Dataprofiler contains GPL licensed code which is in conflict with its own license (Apache 2.0). Specifically: https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/profilers/utils.py#L41-L55

Having this code in Dataprofiler effectively makes the entire project fall under copyleft/GPL and makes it a dependency that an organization not open to GPL python dependencies can't use.

**Comment by taylorfturner** [comment]
Update in #730

**Comment by taylorfturner** [comment]
Issue was resolved in #731 and deployed in `0.8.4`. Thank you.

**Comment by leos** [comment]
Amazing, thank you for the quick turnaround!
