### ISSUE TITLE
Data labeler doesn't allow TextData as the input for the predict

### ISSUE THREAD

**Issue by AnhTruong** [capitalone/DataProfiler#73]
**General Information:**
 - OS: 
 - Python version: 
 - Library version:

**Describe the bug:**
Currently, data labeler allows all returned objects from data reader except TextData. This can be fixed by modifying the check_and_validate_data_format function.

**To Reproduce:**
Run this code
```
data = dp.Data('some_text_file')
predictions = data_labeler.predict(data)
```

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Comment by ChrisWallace2020** [comment]
Currently being handled in PR: https://github.com/capitalone/DataProfiler/pull/55 (not yet merged)
