### ISSUE TITLE
Windows Install error - ValueError: path 'resources/' cannot end with '/

### ISSUE THREAD

**Issue by rxm7706** [capitalone/DataProfiler#738]
https://github.com/capitalone/DataProfiler/blob/5b04b7fe5ee3556235c397efb69b32cd5d364a3b/setup.py#L33

Ran into an install isue 
ValueError: path 'resources/' cannot end with '/

As per 
https://stackoverflow.com/questions/20356482/valueerror-path-conf-cannot-end-with

resource_dir = "resources/"
needs to change to 
resource_dir = "resources"

Thank you.

**Comment by JGSweets** [comment]
@rxm7706 If you are interested in making a PR to fix, we'd be happy to support. Or we can add it to our backlog.
