### ISSUE TITLE
cannot import name 'F1Score' from 'dataprofiler.labelers.character_level_cnn_model'

### ISSUE THREAD

**Issue by brijesh1100** [capitalone/DataProfiler#773]
**General Information:**
 - OS: Windows
 - Python version: 3.10
 - Library version: DataProfiler 0.8.8

**Describe the bug:**
I was just simply running add_new_model_to_data_labeler.ipynb file. not able to import
from dataprofiler.labelers.character_level_cnn_model import CharacterLevelCnnModel, F1Score, \
                                                            create_glove_char, build_embd_dictionary
Getting this error
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[10], line 3
      1 import tensorflow as tf
      2 import numpy as np
----> 3 from dataprofiler.labelers.character_level_cnn_model import CharacterLevelCnnModel, F1Score, \
      4                                                             create_glove_char, build_embd_dictionary
      5 from dataprofiler.labelers.base_model import BaseModel
      7 # CharacterLevelLstmModel derives from CharacterLevelCnnModel
      8 #########################################################
      9 #########################################################

ImportError: cannot import name 'F1Score' from 'dataprofiler.labelers.character_level_cnn_model' 

**To Reproduce:**

**Expected behavior:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/14902544/227285239-65775281-a27e-4107-9cbe-abd76e6ce6b9.png)

**Additional context:**

**Comment by JGSweets** [comment]
Yup! That's a bug. We moved `F1Score` to `dataprofiler.labelers.labeler_utils`.

If you want to make a PR to fix, glad to accept, otherwise we can shortly as well.

Thanks for identifying @brijesh1100 .

**Comment by brijesh1100** [comment]
Sure will happy create a PR

**Comment by JGSweets** [comment]
@brijesh1100 do you still want to make a PR?

**Comment by taylorfturner** [comment]
@brijesh1100 bump on this to make sure it doesn't go stale. Thx!

**Comment by mxnavid** [comment]
Addressed this issue in this PR: https://github.com/capitalone/DataProfiler/pull/952

**Comment by taylorfturner** [comment]
> Addressed this issue in this PR: #952

Thanks, @mxnavid

**Comment by ksneab7** [comment]
Addressed this issue in this PR: https://github.com/capitalone/DataProfiler/pull/952
