### ISSUE TITLE
Create option for num_quantiles attribute

### ISSUE THREAD

**Issue by ksneab7** [capitalone/DataProfiler#853]
**Is your feature request related to a problem? Please describe.**
There is currently no way for a user to set the `num_quantiles` attribute in `NumericStatsMixin`. This could be useful to set by the user and should be allowed through an optional parameter

**Describe the outcome you'd like:**
An option to set the num_quantiles` attribute in `NumericStatsMixin` is created and can be set on initialization

**Additional context:**
This story is in respect to the TODO comment on line 82 in `dataprofiler/profilers/numerical_column_stats.py`

**Comment by taylorfturner** [comment]
@clee1152 working to rebase with dev so this feature gets into `dev`. once merged to Dev, will close

**Comment by ksneab7** [comment]
I
