### ISSUE TITLE
RowStatisticsOptions: Add null row count

### ISSUE THREAD

**Issue by micdavis** [capitalone/DataProfiler#859]
**Is your feature request related to a problem? Please describe.**
RowStatisticsOptions has a `unique_count` option which toggles the calculation of "duplicate_row_count" and "unique row_ratio". But it doesn't have a `null_row_count` option. We need `null_row_count` to be an option to toggle to functionality for `row_has_null_ratio` ([link](https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/profilers/profile_builder.py#L1899)) and `row_is_null_ratio` ([link](https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/profilers/profile_builder.py#L1899)). This option should be toggled in `_update_row_statistics` as well to manage the calculation of these metrics ([link](https://github.com/capitalone/DataProfiler/blob/main/dataprofiler/profilers/profile_builder.py#L1942)).

**Describe the outcome you'd like:**
RowStatisticsOptions needs to include a toggle to enable or disable the calculation for null row count. This option then should be used to the `profiler_builder` to toggle this functionality.

**Additional context:**
This is a follow up from current/previous work on RowStatisticsOptions: #841

**Comment by taylorfturner** [comment]
Closing since the above references PRs were put into `dev` through `staging/dev/options` PR #909
